@@ -4,12 +4,12 @@
 
 # Assembler
 ASM=ARGSFXX
-# Setup heap for SASM and export symbols to symbols.txt
-ASMFLAGS= -e__heap=14400 -xsymbols.txt
+# Setup heap for SASM and export symbols for ARGSFX
+ASMFLAGS= -e__heap=14400 -z
 
 # Linker
 LINK=ARGLINK
-LOPTS=-b30 -h1024 -t7d
+LOPTS=-b30 -h1024 -t7d -z
 
 # ROM Extender
 EXTEND=EXTEND
@@ -51,7 +54,7 @@
  DATA\2-2.CCR DATA\3-2.CCR DATA\B-HOLE.CCR DATA\CONT-2-G.CCR DATA\CP.CCR DATA\E-TEST2.CCR \
  DATA\FOX-G.CCR DATA\LSB.CCR DATA\OBJ-1-G.CCR DATA\OBJ-4.CCR DATA\OOPS.CCR DATA\STARS.CCR \
  DATA\TI-3-US.CCR DATA\2-3.CCR DATA\3-3.CCR DATA\B-M.CCR DATA\CONT-2.CCR DATA\DEMO.CCR \
- DATA\FOX.CCR DATA\M.CCR DATA\OBJ-1.CCR DATA\T-SP.CCR DATA\TI-3.CCR
+ DATA\FOX.CCR DATA\M.CCR DATA\OBJ-1.CCR DATA\T-SP.CCR DATA\TI-3.CCR DATA\MSUBG.CCR
 
 # Crunched tilemaps
 SCRFILES= DATA\1-3-B.PCR DATA\2-3.PCR DATA\3-2.PCR DATA\B-HOLE.PCR DATA\CONT.PCR DATA\DOG.PCR \
@@ -60,7 +63,7 @@
  DATA\T-SS.PCR DATA\TI-3.PCR DATA\1-4.PCR DATA\2-3H.PCR DATA\3-4.PCR DATA\CONT-2-G.PCR \
  DATA\CP.PCR DATA\E-TEST2.PCR DATA\FS-NI.PCR DATA\M.PCR DATA\OOPS.PCR DATA\STARS.PCR DATA\T-ST.PCR \
  DATA\2-2.PCR DATA\2-4.PCR DATA\AND.PCR DATA\CONT-2.PCR DATA\DEMO.PCR DATA\HOLE-A.PCR DATA\MAP.PCR \
- DATA\T-F-S.PCR DATA\TI-3-G.PCR
+ DATA\T-F-S.PCR DATA\TI-3-G.PCR DATA\MSUBG.PCR
 
 #!! If you add/remove a font, make sure to add/remove the corresponding file.
 
@@ -75,7 +78,7 @@
 
 # Recipe to assemble a .ASM file and create a linkable .SOB file
 .asm.sob:
-	@$(ASM) $(NOANSI) -m30 $(ASMFLAGS) $< -v$*.SOB
+	@$(ASM) $(NOANSI) -eFAST=$(fast) -m30 $(ASMFLAGS) $< -v$*.SOB
 
 # Recipes to crunch graphics
 .cgx.ccr:
@@ -93,6 +96,7 @@
 
 setup:
 	@del BANK\*.SOB
+	@del BANK\*.MAP
 
 # Recipe to crunch palettes
 allcols:
@@ -126,13 +130,16 @@
 	@$(LINK) $(LOPTS) -o$@ @flist
 	@$(EXTEND) $@ $(EXTOPS)
 	@$(CHECK) $(COPTS) $@
-	@del msgs.txt
 
 # Actions to perform when assembly is completed
 donebld:
+	@del msgs.txt
 	@del BANK\*.SOB
+	@del BANK\*.MAP
 	@copy sf.sfc ..\SF.SFC
 	@del sf.sfc
+	@$(MAPDEC) SF.MAP SYMBOLS.TXT
+	@del SF.MAP
 	@copy symbols.txt ..\symbols.txt
 	@del symbols.txt
 	@copy BANKS.CSV ..\BANKS.CSV
@@ -141,6 +148,7 @@
 # Clean everything up
 clean:
 	@del BANK\*.SOB
+	@del BANK\*.MAP
 	@del MSPRITES\*.BIN
 	@del DATA\COL\ALLCOLS.COL
 	@del DATA\COL\*.PAC
