SFCONV_VER := 0.11.0
SFCONV_OUT := build/release
SFCONV_EXE := TOOLS/SuperFamiconv-$(SFCONV_VER)/$(SFCONV_OUT)/superfamiconv
ifneq (,$(wildcard /etc/alpine-release))
  INSTALL_FLAGS := -p
else
  ifeq ("Darwin",$(shell uname))
    INSTALL_FLAGS := -CSv
  else
    INSTALL_FLAGS := -Cv
  endif
endif 

${HOME}/.cargo/bin/cargo:
	curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

usb2snes-cli/Cargo.toml:
	git clone https://github.com/Hyphen-ated/usb2snes-cli.git

usb2snes-cli/target/debug/usb2snes-cli: ${HOME}/.cargo/bin/cargo usb2snes-cli/Cargo.toml
	cd usb2snes-cli && ${HOME}/.cargo/bin/cargo build && cd ..

usb2snes-cli.bin: usb2snes-cli/target/debug/usb2snes-cli
	install $(INSTALL_FLAGS) ./usb2snes-cli/target/debug/usb2snes-cli ./usb2snes-cli.bin

SF.SFC:
	$(MAKE) -f Makefile all

send: SF.SFC usb2snes-cli.bin
	@echo 'UPLOADING TO SNES, DO NOT CLOSE THIS WINDOW'
	./usb2snes-cli.bin --upload SF.SFC --path ./SF.SFC
	./usb2snes-cli.bin --boot ./SF.SFC

tools:
	$(MAKE) -C TOOLS all

clean-sf:
	$(MAKE) -f Makefile clean

clean: clean-sf
	rm -f usb2snes-cli.bin
	$(MAKE) -C TOOLS clean
	$(MAKE) -f Makefile.release clean
	cd usb2snes-cli && ${HOME}/.cargo/bin/cargo clean && cd ..

distclean: clean-sf
	rm -f usb2snes-cli.bin
	rm -rf usb2snes-cli
	$(MAKE) -C TOOLS distclean
	$(MAKE) -f Makefile.release distclean

nowindows:
	rm -f dosbox-x.exe
	rm -f usb2snes-cli.exe
	rm -f flips.exe
	$(MAKE) -C TOOLS nowindows

nodosdupes: nodosdup.sh
	sh ./nodosdup.sh

permissions:
	chmod -x CHANGES *.* */*.*
	chmod +x 'optionalstuff/textures/sg.rom 09-23-92/'
	chmod -x */*/*/*.*
	chmod +x "TOOLS/SuperFamiconv-$(SFCONV_VER)" || true
	chmod +x TOOLS/*.src
	chmod -x */*/*.*
	chmod +x 'optionalstuff/textures/sg.rom 09-23-92/'
	chmod +x "TOOLS/SuperFamiconv-$(SFCONV_VER)" || true
	chmod +x TOOLS/*.src
	chmod +x *.sh */*/*.sh

lineendings:
	unix2dos -q TOOLS/*/*.bat
	unix2dos -q optionalstuff/textures/*/make.bat
	unix2dos -q *.BAT *.cmd
	unix2dos -q SF/DATA/COL/MC.BAT
	unix2dos -q -f SF/Makefile 
	unix2dos -q SF/FLIST SF/VERSION.INC
	unix2dos -q -f SF/*/*.ASM
	unix2dos -q -f SF/*/*.INC
	unix2dos -q -f SF/DATA/FONT/MOJI_*.TRN
	unix2dos -q -f SF/*/*.EXT
	unix2dos -q -f SF/MARIO/*.MC
	unix2dos -q TOOLS/Makefile.djg
	unix2dos -q TOOLS/*.bat
	dos2unix -q -e Makefile TOOLS/Makefile
	dos2unix -q -e TOOLS/*/Makefile
	dos2unix -q -e *.sh TOOLS/*/*.sh
	dos2unix -q -e Makefile.*

prebuild: SF/DATA/CONT-2-F.CGX SF/DATA/MAP-F.CGX SF/DATA/OBJ-1-F.CGX SF/DATA/OBJ-2-F.CGX SF/DATA/FOX-F.CGX SF/DATA/CP-FF.CGX
	@echo "French graphics conversion done"
	
$(SFCONV_EXE): TOOLS/Makefile
	$(MAKE) -C TOOLS "bgconv/bin/superfamiconv"

SF/DATA/CONT-2-F.CGX: SF/DATA/CONT-2-F.png $(SFCONV_EXE)
	$(SFCONV_EXE) -v -i SF/DATA/CONT-2-F.png -B 4 -R -D -t $@

SF/DATA/MAP-F.CGX: SF/DATA/MAP-F.png $(SFCONV_EXE)
	$(SFCONV_EXE) -v -i SF/DATA/MAP-F.png -B 4 -R -D -t $@

SF/DATA/OBJ-1-F.CGX: SF/DATA/OBJ-1-F.png $(SFCONV_EXE)
	$(SFCONV_EXE) -v -i SF/DATA/OBJ-1-F.png -B 4 -R -D -t $@

SF/DATA/OBJ-2-F.CGX: SF/DATA/OBJ-2-F.png $(SFCONV_EXE)
	$(SFCONV_EXE) -v -i SF/DATA/OBJ-2-F.png -B 4 -R -D -t $@

SF/DATA/FOX-F.CGX: SF/DATA/FOX-F.png $(SFCONV_EXE)
	$(SFCONV_EXE) -v -i SF/DATA/FOX-F.png -B 4 -R -D -t SF/DATA/FOX-F.CGX

SF/DATA/CP-P.CGX: SF/DATA/CP-P.png $(SFCONV_EXE)
	$(SFCONV_EXE) -v -i SF/DATA/CP-P.png -B 4 -R -D -t SF/DATA/CP-P.CGX

SF/DATA/CP-FF.CGX: SF/DATA/CP-FF.png $(SFCONV_EXE)
	$(SFCONV_EXE) -v -i SF/DATA/CP-FF.png -B 4 -R -D -t $@

mrproper: distclean nowindows permissions nodosdupes

help:
	@echo "Available targets: SF.SFC tools clean distclean nowindows permissions mrproper prebuild lineendings"

.PHONY: tools clean distclean nowindows permissions mrproper prebuild lineendings help
