SFCONV_VER := 0.11.0
SFCONV_OUT := build/release
SFCONV_EXE := TOOLS/SuperFamiconv-$(SFCONV_VER)/$(SFCONV_OUT)/superfamiconv

${HOME}/.cargo/bin/cargo:
	curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

usb2snes-cli/Cargo.toml:
	git clone https://github.com/Hyphen-ated/usb2snes-cli.git

usb2snes-cli/target/debug/usb2snes-cli: ${HOME}/.cargo/bin/cargo usb2snes-cli/Cargo.toml
	cd usb2snes-cli && ${HOME}/.cargo/bin/cargo build && cd ..

usb2snes-cli.bin: usb2snes-cli/target/debug/usb2snes-cli
	install -CS ./usb2snes-cli/target/debug/usb2snes-cli ./usb2snes-cli.bin

SF.SFC:
	$(MAKE) -f Makefile all

send: SF.SFC usb2snes-cli.bin
	@echo 'UPLOADING TO SNES, DO NOT CLOSE THIS WINDOW'
	./usb2snes-cli.bin --upload SF.SFC --path ./SF.SFC
	./usb2snes-cli.bin --boot ./SF.SFC

tools:
	$(MAKE) -C TOOLS all

clean-sf:
	$(MAKE) -f Makefile clean

clean: clean-sf
	rm -f usb2snes-cli.bin
	$(MAKE) -C TOOLS clean
	cd usb2snes-cli && ${HOME}/.cargo/bin/cargo clean && cd ..

distclean: clean-sf
	rm -f usb2snes-cli.bin
	rm -rf usb2snes-cli
	$(MAKE) -C TOOLS distclean

nowindows:
	rm -f dosbox-x.exe
	rm -f usb2snes-cli.exe
	$(MAKE) -C TOOLS nowindows

permissions:
	chmod +x 'optionalstuff/textures/sg.rom 09-23-92/'
	chmod -x CHANGES *.* */*.* */*/*.* */*/*/*.*
	chmod +x 'optionalstuff/textures/sg.rom 09-23-92/'
	chmod +x *.sh */*/*.sh

prebuild: SF/DATA/CONT-2-F.CGX SF/DATA/MAP-F.CGX SF/DATA/OBJ-1-F.CGX SF/DATA/OBJ-2-F.CGX SF/DATA/FOX-F.CGX 
	true
	
$(SFCONV_EXE): TOOLS/Makefile
	$(MAKE) -C TOOLS "bgconv/bin/superfamiconv"

SF/DATA/CONT-2-F.CGX: SF/DATA/CONT-2-F.png $(SFCONV_EXE)
	$(SFCONV_EXE) -v -i SF/DATA/CONT-2-F.png -B 4 -R -D -t SF/DATA/CONT-2-F.CGX

SF/DATA/MAP-F.CGX: SF/DATA/MAP-F.png $(SFCONV_EXE)
	$(SFCONV_EXE) -v -i SF/DATA/MAP-F.png -B 4 -R -D -t SF/DATA/MAP-F.CGX

SF/DATA/OBJ-1-F.CGX: SF/DATA/OBJ-1-F.png $(SFCONV_EXE)
	$(SFCONV_EXE) -v -i SF/DATA/OBJ-1-F.png -B 4 -R -D -t SF/DATA/OBJ-1-F.CGX

SF/DATA/OBJ-2-F.CGX: SF/DATA/OBJ-2-F.png $(SFCONV_EXE)
	$(SFCONV_EXE) -v -i SF/DATA/OBJ-2-F.png -B 4 -R -D -t SF/DATA/OBJ-2-F.CGX

SF/DATA/FOX-F.CGX: SF/DATA/FOX-F.png $(SFCONV_EXE)
	$(SFCONV_EXE) -v -i SF/DATA/FOX-F.png -B 4 -R -D -t SF/DATA/FOX-F.CGX

mrproper: distclean nowindows permissions

.PHONY: tools clean distclean nowindows permissions mrproper prebuild
