VER := 2.2
# flips make-macos.sh fails to build and also uses ricer optimization flags
# Introduce saner optimization flags and hardening ones too
# https://best.openssf.org/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.html
CFLAGS_OPTIM := -O2 -pipe -fomit-frame-pointer
CFLAGS_WARN := -Wall -Wformat -Wformat=2 -Wconversion -Wimplicit-fallthrough -Werror=format-security \
-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 \
-fstrict-flex-arrays=3 \
-fstack-protector-strong \
-fno-delete-null-pointer-checks -fno-strict-overflow -fno-strict-aliasing -ftrivial-auto-var-init=zero \
-Werror=implicit -Werror=incompatible-pointer-types -Werror=int-conversion
CXXFLAGS_OPTIM := $(CFLAGS_OPTIM) -fvisibility=hidden
CXXFLAGS_WARN := $(CFLAGS_WARN) -D_GLIBCXX_ASSERTIONS

all: releases/Release\ $(VER)/USA\ Patches/UltraStarFox\ (USA)\ $(VER).bps releases/Release\ $(VER)/USA\ Patches/UltraStarFox\ (USA)\ (Rev\ 1)\ $(VER).bps releases/Release\ $(VER)/USA\ Patches/UltraStarFox\ (USA)\ (Rev\ 2)\ $(VER).bps releases/Release\ $(VER)/Japan\ Patches/UltraStarFox\ (Japan)\ $(VER).bps releases/Release\ $(VER)/Japan\ Patches/UltraStarFox\ (Japan)\ (Rev\ 1)\ $(VER).bps releases/Release\ $(VER)/PAL\ Patches/UltraStarFox\ (Europe)\ $(VER).bps releases/Release\ $(VER)/PAL\ Patches/UltraStarFox\ (Europe)\ (Rev\ 1)\ $(VER).bps releases/Release\ $(VER)/PAL\ Patches/UltraStarFox\ (Germany)\ $(VER).bps
	sha256sum SF-*.SFC
	@echo "All done!"

french: releases/Release\ $(VER)/USA\ Patches/UltraStarFox\ (USA\ to\ Canada)\ (Rev\ 2)\ $(VER).bps releases/Release\ $(VER)/PAL\ Patches/UltraStarFox\ (Europe\ to\ France)\ (Rev\ 1)\ $(VER).bps
	sha256sum SF-*.SFC
	@echo "Slippy peut jouer des deux bords de l'Atlantique"

spanish: releases/Release\ $(VER)/PAL\ Patches/UltraStarFox\ (Europe\ to\ Spain)\ (Rev\ 1)\ $(VER).bps
	sha256sum SF-*.SFC
	@echo "Ahora, no hay solamente Vortex en castellano"

roms: SF-U.SFC SF-J.SFC SF-E.SFC SF-G.SFC
	sha256sum SF-*.SFC
	@echo "UltraStarFox ROMs built"

allroms: SF-U.SFC SF-J.SFC SF-E.SFC SF-G.SFC SF-F.SFC SF-FC.SFC SF-S.SFC
	sha256sum SF-*.SFC
	@echo "UltraStarFox ROMs (with French and Spanish) built"

# The UltraStarFox builds cannot be done in parallel because its build 
# system can only use the same intermediate directory. Do not replace 
# make with $(MAKE) for this reason
SF-U.SFC: SF/CONFIG/REL_USA.INC
	cp -f $< SF/CONFIG/RELEASE.INC
	make -f Makefile
	mv SF.SFC $@

SF-J.SFC: SF/CONFIG/REL_JPN.INC
	cp -f $< SF/CONFIG/RELEASE.INC
	make -f Makefile
	mv SF.SFC $@

SF-E.SFC: SF/CONFIG/REL_EEE.INC
	cp -f $< SF/CONFIG/RELEASE.INC
	make -f Makefile
	mv SF.SFC $@

SF-G.SFC: SF/CONFIG/REL_DEU.INC
	cp -f $< SF/CONFIG/RELEASE.INC
	make -f Makefile
	mv SF.SFC $@

SF-F.SFC: SF/CONFIG/REL_FRA.INC
	cp -f $< SF/CONFIG/RELEASE.INC
	make -f Makefile
	mv SF.SFC $@

SF-FC.SFC: SF/CONFIG/REL_CAN.INC
	cp -f $< SF/CONFIG/RELEASE.INC
	make -f Makefile
	mv SF.SFC $@

SF-S.SFC: SF/CONFIG/REL_ESP.INC
	cp -f $< SF/CONFIG/RELEASE.INC
	make -f Makefile
	mv SF.SFC $@

releases/Release\ $(VER)/USA\ Patches:
	mkdir -p "$@"

releases/Release\ $(VER)/Japan\ Patches:
	mkdir -p "$@"

releases/Release\ $(VER)/PAL\ Patches:
	mkdir -p "$@"

flips-latest.tar.gz:
	curl https://git.disroot.org/Sir_Walrus/Flips/archive/master.tar.gz -o $@

flips/Makefile: flips-latest.tar.gz
	tar -zxf $<

flips/flips: flips/Makefile
	# Flips is written in C++ but uses CFLAGS for C++ optimization flags
	$(MAKE) -C flips "CFLAGS=$(CXXFLAGS_OPTIM) $(CXXFLAGS_WARN)"

releases/Release\ $(VER)/USA\ Patches/UltraStarFox\ (USA)\ $(VER).bps: flips/flips baseroms/Star\ Fox\ (USA).sfc SF-U.SFC releases/Release\ $(VER)/USA\ Patches
	@echo "Making USA rev 0 patches..."
	./flips/flips --create --bps-delta "./baseroms/Star Fox (USA).sfc" SF-U.SFC "$@"

releases/Release\ $(VER)/USA\ Patches/UltraStarFox\ (USA)\ (Rev\ 1)\ $(VER).bps: flips/flips baseroms/Star\ Fox\ (USA)\ (Rev\ 1).sfc SF-U.SFC releases/Release\ $(VER)/USA\ Patches
	@echo "Making USA rev 1 patches..."
	./flips/flips --create --bps-delta "./baseroms/Star Fox (USA) (Rev 1).sfc" SF-U.SFC "$@"

releases/Release\ $(VER)/USA\ Patches/UltraStarFox\ (USA)\ (Rev\ 2)\ $(VER).bps: flips/flips baseroms/Star\ Fox\ (USA)\ (Rev\ 2).sfc SF-U.SFC releases/Release\ $(VER)/USA\ Patches
	@echo "Making USA rev 2 patches..."
	./flips/flips --create --bps-delta "./baseroms/Star Fox (USA) (Rev 2).sfc" SF-U.SFC "$@"

releases/Release\ $(VER)/USA\ Patches/UltraStarFox\ (USA\ to\ Canada)\ (Rev\ 2)\ $(VER).bps: flips/flips baseroms/Star\ Fox\ (USA)\ (Rev\ 2).sfc SF-FC.SFC releases/Release\ $(VER)/USA\ Patches
	@echo "Making USA rev 2 to Canada French patches..."
	./flips/flips --create --bps-delta "./baseroms/Star Fox (USA) (Rev 2).sfc" SF-FC.SFC "$@"

releases/Release\ $(VER)/Japan\ Patches/UltraStarFox\ (Japan)\ $(VER).bps: flips/flips baseroms/Star\ Fox\ (Japan).sfc SF-J.SFC releases/Release\ $(VER)/Japan\ Patches
	@echo "Making JP rev 0 patches..."
	./flips/flips --create --bps-delta "./baseroms/Star Fox (Japan).sfc" SF-J.SFC "$@"

releases/Release\ $(VER)/Japan\ Patches/UltraStarFox\ (Japan)\ (Rev\ 1)\ $(VER).bps: flips/flips baseroms/Star\ Fox\ (Japan)\ (Rev\ 1).sfc SF-J.SFC releases/Release\ $(VER)/Japan\ Patches
	@echo "Making JP rev 1 patches..."
	./flips/flips --create --bps-delta "./baseroms/Star Fox (Japan) (Rev 1).sfc" SF-J.SFC "$@"

releases/Release\ $(VER)/PAL\ Patches/UltraStarFox\ (Europe)\ $(VER).bps: flips/flips baseroms/Starwing\ (Europe).sfc SF-E.SFC releases/Release\ $(VER)/PAL\ Patches
	@echo "Making PAL rev 0 patches..."
	./flips/flips --create --bps-delta "./baseroms/Starwing (Europe).sfc" SF-E.SFC "$@"

releases/Release\ $(VER)/PAL\ Patches/UltraStarFox\ (Europe)\ (Rev\ 1)\ $(VER).bps: flips/flips baseroms/Starwing\ (Europe)\ (Rev\ 1).sfc SF-E.SFC releases/Release\ $(VER)/PAL\ Patches
	@echo "Making PAL rev 1 patches..."
	./flips/flips --create --bps-delta "./baseroms/Starwing (Europe) (Rev 1).sfc" SF-E.SFC "$@"

releases/Release\ $(VER)/PAL\ Patches/UltraStarFox\ (Europe\ to\ France)\ (Rev\ 1)\ $(VER).bps: flips/flips baseroms/Starwing\ (Europe)\ (Rev\ 1).sfc SF-F.SFC releases/Release\ $(VER)/PAL\ Patches
	@echo "Making PAL rev 1 to PAL-F patches..."
	./flips/flips --create --bps-delta "./baseroms/Starwing (Europe) (Rev 1).sfc" SF-F.SFC "$@"

releases/Release\ $(VER)/PAL\ Patches/UltraStarFox\ (Europe\ to\ Spain)\ (Rev\ 1)\ $(VER).bps: flips/flips baseroms/Starwing\ (Europe)\ (Rev\ 1).sfc SF-S.SFC releases/Release\ $(VER)/PAL\ Patches
	@echo "Making PAL rev 1 to PAL-S patches..."
	./flips/flips --create --bps-delta "./baseroms/Starwing (Europe) (Rev 1).sfc" SF-S.SFC "$@"

releases/Release\ $(VER)/PAL\ Patches/UltraStarFox\ (Germany)\ $(VER).bps: flips/flips baseroms/Starwing\ (Germany).sfc SF-G.SFC releases/Release\ $(VER)/PAL\ Patches
	@echo "Making PAL-G patches..."
	./flips/flips --create --bps-delta "./baseroms/Starwing (Germany).sfc" SF-G.SFC "$@"

clean-sf:
	$(MAKE) -f Makefile clean
	rm -f SF/CONFIG/RELEASE.INC

 # flips Makefile is broken
clean-flips:
	$(MAKE) -C flips clean
	rm -f flips/flips

clean-patches:
	rm -f SF-U.SFC
	rm -f SF-J.SFC
	rm -f SF-E.SFC
	rm -f SF-G.SFC
	rm -f SF-F.SFC
	rm -f SF-C.SFC
	rm -f SF-FC.SFC
	rm -f SF-S.SFC
	rm -f releases/Release*/*Patches/UltraStarFox*.bps

clean: clean-sf clean-patches clean-flips
	true

# No need to call make clean on flips when its directory gets deleted
distclean: clean-sf clean-patches
	rm -rf flips/	

mrproper: distclean
	rm -f flips-latest.tar.gz

help:
	@echo "Available targets: all clean distclean mrproper roms allroms french"

.PHONY: all clean distclean mrproper clean-sf clean-flips clean-patches roms allroms help
