; ################################
; ## UltraStarFox Configuration ##
; ################################

; Release config for a Japan ROM. See comments in related files for explanations.

; GRAPHICS.INC
titlelogo	=	0
controlsscreenpal	=	0
scoretextypos	=	24	; Japan-specific

; ROM.INC
japan	=	1
pal	=	0
gamename	=	2

; LANGUAGE.INC
JAPANESE	=	1
german	=	0
french	=	0
spanish	=	0
