## Makefile for DOS tools built with DJGPP
## Intended for GNU make (especially its DJGPP port)

CC := gcc
CXX := gpp
# Note : you cannot use -pipe with DOS
CFLAGS_OPTIM := -O2 -fomit-frame-pointer -march=pentium3 -s
CFLAGS_WARN := -Wall -Wformat -Wformat=2 -Wconversion -Wimplicit-fallthrough -Werror=format-security \
-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 \
-fstrict-flex-arrays=3 \
-fstack-protector-strong \
-fno-delete-null-pointer-checks -fno-strict-overflow -fno-strict-aliasing -ftrivial-auto-var-init=zero \
-Werror=implicit -Werror=incompatible-pointer-types -Werror=int-conversion \
-fstack-clash-protection -Wtrampolines -fzero-init-padding-bits=all -Wbidi-chars=any
CXXFLAGS_OPTIM := $(CFLAGS_OPTIM) -fvisibility=hidden
CXXFLAGS_WARN := $(CFLAGS_WARN) -D_GLIBCXX_ASSERTIONS

# Use spaces ONLY to indent inside conditionals
# Long file paths not recognized in DOS
ifneq ($(strip ${DJGPP}),)
  $(info "DJGPP environment detected, use 8.3 names")
  # 8.3 paths for DOS (short names as shown in Windows 98)
  SRC_CHRMAP := chrmap~1/Chrmap.c
  SRC_SFCRUNCH := cru_src/sf_cru~1.c
  SRC_SFDECRUNCH := cru_src/sf_dec~1.c
  SRC_EXTEND := extend~1/romExt~1.c
  SRC_FOXFONT := Fontconv/foxfon~1/Foxfont.c
  SRC_INCCOL := inccol~1/inccol.c
  SRC_MAKECOL := inccol~1/Makecol.c
  SRC_APENDCOL := inccol~1/apendcol.c
  SRC_MAPDEC := mapdec~1/argona~1.c
  SRC_CGX2FX := cgx2fx~1/Cgx2fx.c
  SRC_FX2CGX := cgx2fx~1/Fx2cgx.c
  # Other setup. Note: "del" must be lowercase even in DOS
  RM := del
  CP := copy /y
  DIRSEP := \\
else
  $(info "Other envrionment with long file names")
  SRC_CHRMAP := chrmap_src/Chrmap.c
  SRC_SFCRUNCH := cru_src/sf_crunch_mod.c
  SRC_SFDECRUNCH := cru_src/sf_decrunch.c
  SRC_EXTEND := extend_src/romExtenderv2.c
  SRC_FOXFONT := Fontconv/foxfont_source/Foxfont.c
  SRC_INCCOL := inccol_src/inccol.c
  SRC_MAKECOL := inccol_src/Makecol.c
  SRC_APENDCOL := inccol_src/apendcol.c
  SRC_MAPDEC := mapdec_src/argonautmapdecoder.c
  SRC_CGX2FX := cgx2fx_fx2cgx_src/Cgx2fx.c
  SRC_FX2CGX := cgx2fx_fx2cgx_src/Fx2cgx.c
  # Windows 9x, go the DJGPP route please
  # I really mean an NT-based Windows here
  ifeq (${OS},Windows_NT)
    $(info "NT-based Windows")
    RM := del /q
    CP := copy /y
    DIRSEP := \\
  else
    # *nix assumed here
    MY_NIX := $(shell uname)
    $(info "$(MY_NIX)")
    RM := rm -f
    ifneq (,$(wildcard /etc/alpine-release))
      CP := install -p
    else
      ifeq ("Darwin",$(MY_NIX))
        CP := install -CSv
      else
        CP := install -Cv
      endif
    endif
    DIRSEP := /
  endif
endif

COMPILE := $(CC) $(CFLAGS_OPTIM) $(CFLAGS_WARN)
DESTBIN := ..$(DIRSEP)bin$(DIRSEP)

# Commands to build targets (BELOW) must be indented with tabs, never spaces

all: $(DESTBIN)chrmap.exe $(DESTBIN)cru.exe $(DESTBIN)extend.exe $(DESTBIN)fon.exe $(DESTBIN)inccol.exe $(DESTBIN)makecol.exe $(DESTBIN)apendcol.exe $(DESTBIN)mapdec.exe cgx2fx.exe $(DESTBIN)cgx2fx.exe fx2cgx.exe

$(DESTBIN)chrmap.exe: $(SRC_CHRMAP)
	$(COMPILE) $< -o $@

cru.exe: $(SRC_SFCRUNCH)
	$(COMPILE) $< -o $@

$(DESTBIN)cru.exe: cru.exe
	$(CP) $@ $(DESTBIN)

$(DESTBIN)extend.exe: $(SRC_EXTEND)
	$(COMPILE) $< -o $@

$(DESTBIN)fon.exe: $(SRC_FOXFONT)
	$(COMPILE) $< -o $@

$(DESTBIN)inccol.exe: $(SRC_INCCOL)
	$(COMPILE) $< -o $@

$(DESTBIN)makecol.exe: $(SRC_MAKECOL)
	$(COMPILE) $< -o $@

$(DESTBIN)apendcol.exe: $(SRC_APENDCOL)
	$(COMPILE) $< -o $@

$(DESTBIN)mapdec.exe: $(SRC_MAPDEC)
	$(COMPILE) $< -o $@

# Source for $(DESTBIN)sfcheck.exe is at https://www.github.com/Optiroc/SuperFamicheck/
# 4 very C++ files. The static C++ library explains why the DOS binary is so big.

cgx2fx.exe: $(SRC_CGX2FX)
	$(COMPILE) $< -o $@

$(DESTBIN)cgx2fx.exe: cgx2fx.exe
	$(CP) $@ $(DESTBIN)

fx2cgx.exe: $(SRC_FX2CGX)
	$(COMPILE) $< -o $@

decru.exe: $(SRC_SFDERUNCH)
	$(COMPILE) $< -o $@

# Do not delete existing DJGPP executables inside BIN with clean,
# as they are needed for almost every UltraStarfox user.
# apendcol.exe is an added executable in Repzilon's fork.
clean:
	$(RM) cgx2fx.exe
	$(RM) fx2cgx.exe
	$(RM) $(DESTBIN)apendcol.exe
	$(RM) cru.exe
	$(RM) decru.exe

distclean: clean
	$(RM) $(DESTBIN)chrmap.exe
	$(RM) $(DESTBIN)cru.exe
	$(RM) $(DESTBIN)extend.exe
	$(RM) $(DESTBIN)fon.exe
	$(RM) $(DESTBIN)inccol.exe
	$(RM) $(DESTBIN)makecol.exe
	$(RM) $(DESTBIN)mapdec.exe
	$(RM) $(DESTBIN)cgx2fx.exe

help:
	@echo "Available targets: all clean distclean"

.PHONY: all clean distclean help
