## Makefile for DOS tools built with DJGPP
## Intended for GNU make (especially its DJGPP port)

CC := gcc
CXX := gpp
# Note : you cannot use -pipe with DOS
CFLAGS_OPTIM := -O2 -fomit-frame-pointer -march=pentium3 -s
CFLAGS_HARDEN := -Wall -Wformat -Wformat=2 -Wconversion -Wimplicit-fallthrough -Werror=format-security \
-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 \
-fstack-protector-strong \
-fno-delete-null-pointer-checks -fno-strict-overflow -fno-strict-aliasing \
-fstack-clash-protection -Wtrampolines \
-Wno-format-nonliteral -Werror=format-security
# Flags exclusive to C language, not to be used for C++
CCFLAGS_HARDEN := -Werror=implicit -Werror=incompatible-pointer-types -Werror=int-conversion
# -fvisibility=hidden is unavailable on static linking systems (DOS)
CXXFLAGS_OPTIM := $(CFLAGS_OPTIM)
CXXFLAGS_HARDEN := $(CFLAGS_HARDEN) -D_GLIBCXX_ASSERTIONS

# Use spaces ONLY to indent inside conditionals
# Long file paths not recognized in DOS
ifneq ($(strip ${DJGPP}),)
  $(info "DJGPP environment detected, use 8.3 names")
  # 8.3 paths for DOS (short names as shown in Windows 98)
  SRC_CHRMAP := chrmap~1/Chrmap.c
  SRC_SFCRUNCH := cru_src/sf_cru~1.c
  SRC_SFDECRUNCH := cru_src/sf_dec~1.c
  SRC_EXTEND := extend~1/romExt~1.c
  SRC_FOXFONT := Fontconv/foxfon~1/Foxfont.c
  SRC_INCCOL := inccol~2/inccol.c
  SRC_MAKECOL := inccol~2/Makecol.c
  SRC_APENDCOL := inccol~2/apendcol.c
  SRC_MAPDEC := mapdec~1/argona~1.c
  SRC_CGX2FX := cgx2fx~1/Cgx2fx.c
  SRC_FX2CGX := cgx2fx~1/Fx2cgx.c
  SRC_SFCHECK := sfcheck.src/src/sfcRom.cpp sfcheck.src/src/superf~1.cpp
  # Other setup. Note: "del" must be lowercase even in DOS
  RM := del
  CP := copy /y
  DIRSEP := \\
else
  $(info "Other envrionment with long file names")
  SRC_CHRMAP := chrmap_src/Chrmap.c
  SRC_SFCRUNCH := cru_src/sf_crunch_mod.c
  SRC_SFDECRUNCH := cru_src/sf_decrunch.c
  SRC_EXTEND := extend_src/romExtenderv2.c
  SRC_FOXFONT := Fontconv/foxfont_source/Foxfont.c
  SRC_INCCOL := inccol_src/inccol.c
  SRC_MAKECOL := inccol_src/Makecol.c
  SRC_APENDCOL := inccol_src/apendcol.c
  SRC_MAPDEC := mapdec_src/argonautmapdecoder.c
  SRC_CGX2FX := cgx2fx_fx2cgx_src/Cgx2fx.c
  SRC_FX2CGX := cgx2fx_fx2cgx_src/Fx2cgx.c
  SRC_SFCHECK := sfcheck.src/src/sfcRom.cpp sfcheck.src/src/superfamicheck.cpp
  # Windows 9x, go the DJGPP route please
  # I really mean an NT-based Windows here
  ifeq (${OS},Windows_NT)
    $(info "NT-based Windows")
    RM := del /q
    CP := copy /y
    DIRSEP := \\
  else
    # *nix assumed here
    MY_NIX := $(shell uname)
    $(info "$(MY_NIX)")
    RM := rm -f
    ifneq (,$(wildcard /etc/alpine-release))
      CP := install -p
    else
      ifeq ("Darwin",$(MY_NIX))
        CP := install -CSv
      else
        CP := install -Cv
      endif
    endif
    DIRSEP := /
  endif
endif

COMPILE := $(CC) $(CFLAGS_OPTIM) $(CFLAGS_HARDEN)
CPLUSPLUS := $(CXX) $(CXXFLAGS_OPTIM) $(CXXFLAGS_HARDEN)
$(info Compiler and flags: $(COMPILE))
DESTBIN := ..$(DIRSEP)bin$(DIRSEP)
BINDIR := binaries$(DIRSEP)msdos$(DIRSEP)

# Commands to build targets (BELOW) must be indented with tabs, never spaces

all: $(BINDIR)cru.exe $(BINDIR)decru.exe $(BINDIR)cgx2fx.exe $(BINDIR)fx2cgx.exe

install: $(DESTBIN)chrmap.exe $(DESTBIN)cru.exe $(DESTBIN)extend.exe $(DESTBIN)fon.exe $(DESTBIN)inccol.exe $(DESTBIN)makecol.exe $(DESTBIN)apendcol.exe $(DESTBIN)mapdec.exe $(DESTBIN)cgx2fx.exe $(DESTBIN)sfcheck.exe

$(BINDIR)cru.exe: $(SRC_SFCRUNCH)
	$(COMPILE) $< -o $@

$(BINDIR)decru.exe: $(SRC_SFDECRUNCH)
	$(COMPILE) $< -o $@

$(BINDIR)cgx2fx.exe: $(SRC_CGX2FX)
	$(COMPILE) $< -o $@

$(BINDIR)fx2cgx.exe: $(SRC_FX2CGX)
	$(COMPILE) $< -o $@

$(BINDIR)chrmap.exe: $(SRC_CHRMAP)
	$(COMPILE) $< -o $@

$(BINDIR)extend.exe: $(SRC_EXTEND)
	$(COMPILE) $< -o $@

$(BINDIR)fon.exe: $(SRC_FOXFONT)
	$(COMPILE) $< -o $@

$(BINDIR)inccol.exe: $(SRC_INCCOL)
	$(COMPILE) $< -o $@

$(BINDIR)makecol.exe: $(SRC_MAKECOL)
	$(COMPILE) $< -o $@

$(BINDIR)apendcol.exe: $(SRC_APENDCOL)
	$(COMPILE) $< -o $@

$(BINDIR)mapdec.exe: $(SRC_MAPDEC)
	$(COMPILE) $< -o $@

$(DESTBIN)chrmap.exe: $(BINDIR)chrmap.exe
	$(CP) $< $(DESTBIN)

$(DESTBIN)cru.exe: $(BINDIR)cru.exe
	$(CP) $< $(DESTBIN)

$(DESTBIN)extend.exe: $(BINDIR)extend.exe
	$(CP) $< $(DESTBIN)

$(DESTBIN)fon.exe: $(BINDIR)fon.exe
	$(CP) $< $(DESTBIN)

$(DESTBIN)inccol.exe: $(BINDIR)inccol.exe
	$(CP) $< $(DESTBIN)

$(DESTBIN)makecol.exe: $(BINDIR)makecol.exe
	$(CP) $< $(DESTBIN)

$(DESTBIN)apendcol.exe: $(BINDIR)apendcol.exe
	$(CP) $< $(DESTBIN)

$(DESTBIN)mapdec.exe: $(BINDIR)mapdec.exe
	$(CP) $< $(DESTBIN)

$(DESTBIN)cgx2fx.exe: $(BINDIR)cgx2fx.exe
	$(CP) $< $(DESTBIN)

# Source is at https://www.github.com/Optiroc/SuperFamicheck/
# Makefile (not this Makefile.djg) can download it (invoke make sfcheck.tgz).

# DJGPP offers tar and gzip in its v2gnu directory, but not in the Zip picker
sfcheck.src$(DIRSEP)src$(DIRSEP)sfcRom.cpp: sfcheck.tgz
	tar -zxf $<
	ren superf sfcheck.src

# Don't think CMake works for DJGPP
# Two C++ source and 2 C++ headers, and using the STL.
# Mandatory static linking explains why the DOS binary is that big
$(BINDIR)sfcheck.exe: $(SRC_SFCHECK)
	$(CPLUSPLUS) $(SRC_SFCHECK) -o $@

$(DESTBIN)sfcheck.exe: $(BINDIR)sfcheck.exe
	$(CP) $< $(DESTBIN)

# apendcol.exe is an added executable in Repzilon's fork.
clean:
	$(RM) $(BINDIR)cgx2fx.exe
	$(RM) $(BINDIR)fx2cgx.exe
	$(RM) $(DESTBIN)apendcol.exe
	$(RM) $(BINDIR)cru.exe
	$(RM) $(BINDIR)decru.exe
	$(RM) $(BINDIR)sfcheck.exe
	$(RM) $(BINDIR)printf.exe
	$(RM) $(BINDIR)chrmap.exe
	$(RM) $(BINDIR)extend.exe
	$(RM) $(BINDIR)fon.exe
	$(RM) $(BINDIR)inccol.exe
	$(RM) $(BINDIR)makecol.exe
	$(RM) $(BINDIR)apendcol.exe
	$(RM) $(BINDIR)mapdec.exe

distclean: clean
	$(RM) $(DESTBIN)chrmap.exe
	$(RM) $(DESTBIN)cru.exe
	$(RM) $(DESTBIN)extend.exe
	$(RM) $(DESTBIN)fon.exe
	$(RM) $(DESTBIN)inccol.exe
	$(RM) $(DESTBIN)makecol.exe
	$(RM) $(DESTBIN)mapdec.exe
	$(RM) $(DESTBIN)cgx2fx.exe
	$(RM) $(DESTBIN)sfcheck.exe
	$(RM) $(DESTBIN)printf.exe

help:
	@echo "Available targets: all install clean distclean"

.PHONY: all clean install distclean help
